openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: AWS Ground Station Agent Satellite API
  description: Welcome to the AWS Ground Station API Reference. AWS Ground Station is a fully managed service that enables you to control satellite communications, downlink and process satellite data, and scale your satellite operations efficiently and cost-effectively without having to build or manage your own ground station infrastructure.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: groundstation
  x-aws-signingName: groundstation
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/groundstation-2019-05-23.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://groundstation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Ground Station multi-region endpoint
- url: https://groundstation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Ground Station multi-region endpoint
- url: http://groundstation.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Ground Station endpoint for China (Beijing) and China (Ningxia)
- url: https://groundstation.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Ground Station endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Satellite
paths:
  /satellite/{satelliteId}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: GetSatellite
      description: Returns a satellite.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSatelliteResponse'
              examples:
                GetSatellite200Example:
                  summary: Default GetSatellite 200 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
              examples:
                GetSatellite480Example:
                  summary: Default GetSatellite 480 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '481':
          description: DependencyException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependencyException'
              examples:
                GetSatellite481Example:
                  summary: Default GetSatellite 481 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                GetSatellite482Example:
                  summary: Default GetSatellite 482 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
      parameters:
      - name: satelliteId
        in: path
        required: true
        description: UUID of a satellite.
        schema:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
          minLength: 1
          maxLength: 128
      summary: Amazon Ground Station Get Satellite
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Satellite
  /satellite:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListSatellites
      description: Returns a list of satellites.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSatellitesResponse'
              examples:
                ListSatellites200Example:
                  summary: Default ListSatellites 200 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
              examples:
                ListSatellites480Example:
                  summary: Default ListSatellites 480 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '481':
          description: DependencyException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependencyException'
              examples:
                ListSatellites481Example:
                  summary: Default ListSatellites 481 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListSatellites482Example:
                  summary: Default ListSatellites 482 response
                  x-microcks-default: true
                  value:
                    contactId: abc-123
                    contactStatus: COMPLETED
      parameters:
      - name: maxResults
        in: query
        required: false
        description: Maximum number of satellites returned.
        schema:
          type: integer
          minimum: 0
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: Next token that can be supplied in the next call to get the next page of satellites.
        schema:
          type: string
          pattern: ^[A-Za-z0-9-/+_.=]+$
          minLength: 3
          maxLength: 1000
      summary: Amazon Ground Station List Satellites
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Satellite
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceNotFoundException: {}
    Timestamp:
      type: string
      format: date-time
    SatelliteListItem:
      type: object
      properties:
        currentEphemeris:
          allOf:
          - $ref: '#/components/schemas/EphemerisMetaData'
          - description: The current ephemeris being used to compute the trajectory of the satellite.
        groundStations:
          allOf:
          - $ref: '#/components/schemas/GroundStationIdList'
          - description: A list of ground stations to which the satellite is on-boarded.
        noradSatelliteID:
          allOf:
          - $ref: '#/components/schemas/noradSatelliteID'
          - description: NORAD satellite ID number.
        satelliteArn:
          allOf:
          - $ref: '#/components/schemas/satelliteArn'
          - description: ARN of a satellite.
        satelliteId:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          - description: UUID of a satellite.
      description: Item in a list of satellites.
    EphemerisSource:
      type: string
      enum:
      - CUSTOMER_PROVIDED
      - SPACE_TRACK
    InvalidParameterException: {}
    GetSatelliteResponse:
      type: object
      properties:
        currentEphemeris:
          allOf:
          - $ref: '#/components/schemas/EphemerisMetaData'
          - description: The current ephemeris being used to compute the trajectory of the satellite.
        groundStations:
          allOf:
          - $ref: '#/components/schemas/GroundStationIdList'
          - description: A list of ground stations to which the satellite is on-boarded.
        noradSatelliteID:
          allOf:
          - $ref: '#/components/schemas/noradSatelliteID'
          - description: NORAD satellite ID number.
        satelliteArn:
          allOf:
          - $ref: '#/components/schemas/satelliteArn'
          - description: ARN of a satellite.
        satelliteId:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          - description: UUID of a satellite.
      description: <p/>
    SafeName:
      type: string
      pattern: ^[ a-zA-Z0-9_:-]{1,256}$
      minLength: 1
      maxLength: 256
    GroundStationIdList:
      type: array
      items:
        $ref: '#/components/schemas/GroundStationName'
      minItems: 0
      maxItems: 500
    PaginationToken:
      type: string
      pattern: ^[A-Za-z0-9-/+_.=]+$
      minLength: 3
      maxLength: 1000
    noradSatelliteID:
      type: integer
      minimum: 0
      maximum: 99999
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 1
      maxLength: 128
    SatelliteList:
      type: array
      items:
        $ref: '#/components/schemas/SatelliteListItem'
    DependencyException: {}
    ListSatellitesResponse:
      type: object
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: Next token that can be supplied in the next call to get the next page of satellites.
        satellites:
          allOf:
          - $ref: '#/components/schemas/SatelliteList'
          - description: List of satellites.
      description: <p/>
    EphemerisMetaData:
      type: object
      required:
      - source
      properties:
        ephemerisId:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          - description: <p>UUID of a customer-provided ephemeris.</p> <p>This field is not populated for default ephemerides from Space Track.</p>
        epoch:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: <p>The epoch of a default, ephemeris from Space Track in UTC.</p> <p>This field is not populated for customer-provided ephemerides.</p>
        name:
          allOf:
          - $ref: '#/components/schemas/SafeName'
          - description: <p>A name string associated with the ephemeris. Used as a human-readable identifier for the ephemeris.</p> <p>A name is only returned for customer-provider ephemerides that have a name associated.</p>
        source:
          allOf:
          - $ref: '#/components/schemas/EphemerisSource'
          - description: The <code>EphemerisSource</code> that generated a given ephemeris.
      description: Metadata describing a particular ephemeris.
    GroundStationName:
      type: string
      pattern: ^[ a-zA-Z0-9-._:=]{4,256}$
      minLength: 4
      maxLength: 500
    satelliteArn:
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/groundstation/
x-hasEquivalentPaths: true
